"use client";

import { useMemo, useRef, useState } from "react";
import { ArrowRight, Balloon, CakeSlice, CalendarDays, Camera, Check, ChevronDown, Clock3, Gift, Heart, MapPin, Menu, MessageCircle, MoveRight, Palette, Sparkles, Star, X, WandSparkles } from "lucide-react";

const business = { name: "Maria Festa na Mesa", phone: "5511983660749", city: "Osasco, SP", address: "Rua Apóstolo João Batista, nº 16, Jardim Conceição, Osasco - SP", hours: "Seg a sex, 9h às 18h" };
const gallery = [
  { title: "Ursinha princesa", meta: "Tema infantil", image: "/1.jpeg" },
  { title: "Frozen", meta: "Tema infantil", image: "/2.jpeg" },
  { title: "Homem-Aranha", meta: "Tema infantil", image: "/3.jpeg" },
  { title: "Patrulha Canina", meta: "Tema infantil", image: "/4.jpeg" },
  { title: "Azul e dourado", meta: "Aniversário", image: "/5.jpeg" },
];
const faqs = [["O que está incluso em cada pacote?", "Os itens de cada pacote estão listados nos cards acima. Você também pode conversar com a gente sobre itens adicionais."], ["Como funciona o serviço?", "Fornecemos apenas os itens do pacote. A retirada, a organização no local da festa e a devolução ficam por conta de quem contrata."], ["Onde retiro e devolvo os itens?", `A retirada e a devolução são feitas em ${business.address}, por conta de quem contrata. Combine os horários pelo WhatsApp.`], ["Posso escolher qualquer tema?", "Você pode enviar uma referência, escolher cores ou contar a ideia que imaginou. Confirmamos as opções disponíveis pelo WhatsApp."], ["Com quanto tempo preciso reservar?", "Recomendamos consultar com 20 a 30 dias de antecedência. Para datas concorridas, quanto antes melhor."], ["Os balões estão inclusos?", "O arco de balões aparece nos pacotes Encanto e Personalizado. Consulte a disponibilidade de cores e temas."], ["O bolo e os doces estão inclusos?", "Não. Os pacotes incluem apenas os itens de decoração listados em cada card."], ["Como funciona o pagamento?", "São 50% adiantados para confirmar a reserva, sem reembolso, e os 50% restantes no momento da retirada dos itens."], ["Posso adicionar mais itens?", "Sim. O pacote Personalizado pode receber itens extras; consulte as opções e o valor pelo WhatsApp."]];

function whatsapp(message: string) { window.open(`https://wa.me/${business.phone}?text=${encodeURIComponent(message)}`, "_blank", "noopener,noreferrer"); }
function Logo() { return <a href="#inicio" className="logo" aria-label="Maria Festa na Mesa, início"><img src="/logo-maria.png" alt="" aria-hidden="true" width="54" height="54"/><span className="logo-name"><strong>Maria</strong><small>Festa na Mesa</small></span></a>; }

export default function Home() {
  const [menuOpen, setMenuOpen] = useState(false), [selectedImage, setSelectedImage] = useState<typeof gallery[number] | null>(null), [openFaq, setOpenFaq] = useState(0), [availabilityDate, setAvailabilityDate] = useState("");
  const availabilityInput = useRef<HTMLInputElement>(null);
  const dateLabel = availabilityDate ? availabilityDate.split("-").reverse().join("/") : "";
  const checkAvailability = () => { if (!availabilityDate) { availabilityInput.current?.showPicker?.(); availabilityInput.current?.focus(); return; } whatsapp(`Olá! Gostaria de saber se a data ${dateLabel} está disponível para retirar um pacote de decoração.`); };
  const [form, setForm] = useState({ occasion: "Aniversário infantil", theme: "", date: "", package: "Ainda não sei" });
  const formMessage = useMemo(() => `Olá! Gostaria de solicitar um orçamento com a Maria Festa na Mesa.\n\nOcasião: ${form.occasion}\nTema: ${form.theme || "Ainda vou escolher"}\nData: ${form.date || "Ainda não definida"}\nPacote: ${form.package}\n\nVi o trabalho de vocês pelo site.`, [form]);
  const update = (key: keyof typeof form, value: string) => setForm((current) => ({ ...current, [key]: value }));
  return <main>
    <header className="site-header"><div className="container nav-wrap"><Logo/><nav className={menuOpen ? "nav-links is-open" : "nav-links"} aria-label="Navegação principal">{[["Como funciona", "#como-funciona"], ["Decorações", "#decoracoes"], ["Pacotes", "#pacotes"], ["Avaliações", "#avaliacoes"], ["FAQ", "#faq"]].map(([label, href]) => <a key={href} href={href} onClick={() => setMenuOpen(false)}>{label}</a>)}</nav><button className="nav-cta" onClick={() => whatsapp("Olá! Vim pelo site e gostaria de fazer um orçamento.")}>Pedir orçamento <ArrowRight size={16}/></button><button className="menu-button" aria-label="Abrir menu" onClick={() => setMenuOpen(!menuOpen)}>{menuOpen ? <X/> : <Menu/>}</button></div></header>
    <section className="hero" id="inicio"><div className="container hero-grid"><div className="hero-copy"><p className="eyebrow"><span className="eyebrow-line"/> decoração que acolhe</p><h1>Sua festa linda,<br/><em>prática</em> e do seu jeito.</h1><p className="hero-lead">Itens de decoração para você retirar, celebrar do seu jeito e devolver depois da festa.</p><div className="hero-actions"><button className="button button-primary" onClick={() => whatsapp("Olá! Vim pelo site e gostaria de fazer um orçamento.")}>Quero meu orçamento <ArrowRight size={18}/></button><a className="button button-ghost" href="#decoracoes">Ver decorações <MoveRight size={18}/></a></div><div className="trust-row"><div><strong>4.9<span>★</span></strong><span>avaliação média</span></div><div><strong>100%</strong><span>feito com carinho</span></div></div></div><div className="hero-visual"><div className="hero-image"><img src={gallery[0].image} alt="Decoração de ursinha com painel, balões e itens de mesa"/><div className="floating-note"><Sparkles size={15}/><span>cada detalhe<br/><b>pensado para você</b></span></div></div><div className="hero-orb orb-one"/><div className="hero-orb orb-two"/><span className="hero-stamp">feito<br/><b>à mão</b></span></div></div></section>
    <section className="proof-strip"><div className="container proof-items"><span><Palette size={18}/> pacotes personalizados</span><span><WandSparkles size={18}/> temas variados</span><span><MessageCircle size={18}/> atendimento rápido</span><span><CakeSlice size={18}/> ideal para festas em casa</span></div></section>
    <section className="section about" id="sobre"><div className="container about-grid"><div><p className="eyebrow">o encanto está nos detalhes</p><h2>Uma festa bonita<br/><em>sem complicação.</em></h2><p className="section-lead">Escolha os itens que combinam com a sua festa. Você retira em Osasco, usa na comemoração e devolve depois.</p><p className="section-lead">Oferecemos pacotes com painel, boleira, bandejas, displays e outros detalhes para o tema que você escolher.</p><a className="text-link" href="#como-funciona">Entenda como funciona <ArrowRight size={16}/></a></div><div className="step-cards"><div className="step-card"><span>01</span><div><h3>Você escolhe o tema</h3><p>Conte o tema, as cores ou a ideia que você imaginou.</p></div></div><div className="step-card"><span>02</span><div><h3>Nós preparamos tudo</h3><p>Criamos uma composição harmoniosa e personalizada.</p></div></div><div className="step-card"><span>03</span><div><h3>Você retira e devolve</h3><p>A retirada e a devolução dos itens ficam por sua conta.</p></div></div></div></div></section>
    <section className="section gallery-section" id="decoracoes"><div className="container"><div className="section-heading"><div><p className="eyebrow">portfólio</p><h2>Ideias para a sua <em>festa</em></h2></div><p>Veja os temas e itens das nossas festas para inspirar a sua comemoração.</p></div><div className="gallery-grid">{gallery.map((item, index) => <button className={`gallery-item gallery-${index + 1}`} key={item.title} onClick={() => setSelectedImage(item)}><img src={item.image} alt={`${item.title}, ${item.meta}`}/><span className="gallery-caption"><strong>{item.title}</strong><small>{item.meta}</small></span><span className="gallery-plus">+</span></button>)}</div><div className="center-action"><button className="button button-outline" onClick={() => whatsapp("Olá! Gostei de uma decoração do site e gostaria de algo parecido.")}>Quero uma decoração assim <ArrowRight size={17}/></button></div></div></section>
    <section className="section benefits"><div className="container"><div className="section-heading centered"><div><p className="eyebrow">por que a gente</p><h2>Seu momento merece <em>cuidado</em></h2></div></div><div className="benefit-grid">{[[Heart, "Decoração personalizada", "Do tema às cores, tudo conversa com a sua ideia."], [Clock3, "Retirada combinada", "Você retira os itens em Osasco e devolve após a festa."], [Gift, "Opções para cada orçamento", "Uma proposta bonita que respeita o tamanho do seu momento."], [Star, "Composição fotogênica", "Detalhes pensados para render memórias — e fotos lindas."], [MapPin, "Atendimento rápido", "A gente responde suas dúvidas e combina os detalhes da retirada."], [Balloon, "Temas variados", "Do clássico ao criativo, sempre com leveza e bom gosto."]].map(([Icon, title, desc]) => <div className="benefit-card" key={title as string}><span className="icon-bubble"><Icon size={21}/></span><h3>{title as string}</h3><p>{desc as string}</p></div>)}</div></div></section>
    <section className="section packages" id="pacotes"><div className="container"><div className="section-heading"><div><p className="eyebrow">escolha seu jeito</p><h2>Pacotes para celebrar <em>sem estresse</em></h2></div><p>Escolha um pacote e consulte as opções de tema. Retirada e devolução por conta de quem contrata.</p></div><div className="package-grid"><PackageCard title="Essencial" subtitle="Para comemorações simples" items={["1 painel", "1 boleira", "2 bandejas", "1 display"]} onClick={() => whatsapp("Olá! Gostaria de consultar o valor do Pacote Essencial.")}/><PackageCard featured title="Encanto" subtitle="O favorito para uma festa completa" items={["1 painel", "1 arco de balões", "1 boleira", "3 bandejas", "2 displays", "1 vaso"]} onClick={() => whatsapp("Olá! Gostaria de saber mais sobre o Pacote Encanto.")}/><PackageCard title="Personalizado" subtitle="Para uma ideia só sua" items={["1 painel", "1 arco de balões", "1 boleira", "3 bandejas", "1 vaso", "2 displays", "1 guirlanda de balões", "Pode adicionar mais itens"]} onClick={() => whatsapp("Olá! Quero personalizar um pacote para a minha festa.")}/></div><p className="package-terms">Reserva com 50% adiantados, sem reembolso. Os 50% restantes são pagos na retirada. Retirada e devolução dos itens por conta de quem contrata.</p></div></section>
    <section className="section quote-section" id="orcamento"><div className="container quote-grid"><div className="quote-intro"><p className="eyebrow">vamos criar juntos</p><h2>Conte a ideia.<br/><em>Escolha seu pacote.</em></h2><p>Preencha rapidinho para consultar seu pacote pelo WhatsApp. A reserva é confirmada com 50% adiantados, sem reembolso. Os outros 50% são pagos na retirada.</p><div className="quote-note"><Check size={18}/> resposta rápida</div><div className="quote-note"><Check size={18}/> proposta de acordo com seu momento</div><div className="quote-note"><Check size={18}/> atendimento humano</div></div><div className="quote-card"><div className="form-progress"><span>01</span><div><b>Seu orçamento começa aqui</b><small>Leva menos de 1 minuto</small></div><Sparkles size={18}/></div><div className="form-grid"><label>Qual é a ocasião?<select value={form.occasion} onChange={(e) => update("occasion", e.target.value)}>{["Aniversário infantil", "Aniversário adulto", "Chá revelação", "Chá de bebê", "Mesversário", "Outra ocasião"].map((x) => <option key={x}>{x}</option>)}</select></label><label>Qual tema você deseja?<input placeholder="Ex.: Safari, azul e dourado" value={form.theme} onChange={(e) => update("theme", e.target.value)}/></label><label>Quando será a festa?<input type="date" value={form.date} onChange={(e) => update("date", e.target.value)}/></label><label>Qual pacote você deseja?<select value={form.package} onChange={(e) => update("package", e.target.value)}>{["Ainda não sei", "Essencial", "Encanto", "Personalizado"].map((x) => <option key={x}>{x}</option>)}</select></label></div><button className="button button-primary form-submit" onClick={() => whatsapp(formMessage)}>Solicitar orçamento pelo WhatsApp <MessageCircle size={18}/></button><p className="form-footnote">Você será direcionado para uma conversa no WhatsApp.</p></div></div></section>
    <section className="section how" id="como-funciona"><div className="container"><div className="section-heading centered"><div><p className="eyebrow">é simples assim</p><h2>Da reserva à <em>devolução</em></h2></div></div><div className="timeline">{[[MessageCircle, "Consulta data e tema"], [Palette, "Escolhe o pacote"], [CalendarDays, "Paga 50% adiantados, sem reembolso"], [WandSparkles, "Preparamos os itens"], [MapPin, "Você retira e paga os 50% restantes"], [CakeSlice, "Celebra e devolve os itens"]].map(([Icon, text], i) => <div className="timeline-item" key={text as string}><span className="timeline-number">{String(i + 1).padStart(2, "0")}</span><span className="timeline-icon"><Icon size={20}/></span><strong>{text as string}</strong></div>)}</div></div></section>
    <section className="section testimonials" id="avaliacoes"><div className="container"><div className="section-heading"><div><p className="eyebrow">de quem viveu</p><h2>Quem comemora com a gente <em>recomenda</em></h2></div><div className="rating"><span>★★★★★</span><b>4.9/5</b><small>avaliação média</small></div></div><div className="testimonial-grid"><Testimonial name="Mariana S." theme="Safari · 2 anos" text="A mesa ficou ainda mais linda do que eu imaginava. Tudo delicado, organizado e com muito capricho."/><Testimonial name="Camila R." theme="Chá revelação" text="O atendimento foi rápido desde o primeiro contato. Gostei muito das opções de tema."/><Testimonial name="Renata L." theme="Aniversário adulto" text="Encontrei itens para uma decoração elegante na sala de casa, do jeitinho que eu queria."/></div></div></section>
    <section className="section photo-highlight"><div className="container highlight-grid"><div className="highlight-copy"><p className="eyebrow">escolha seu tema</p><h2>Detalhes para uma festa <em>com a sua cara.</em></h2><p>Do azul ao rosa, dos personagens às cores clássicas: veja algumas combinações possíveis e conte sua ideia para a gente.</p><a className="text-link" href="#decoracoes">Explorar as fotos <ArrowRight size={16}/></a></div><div className="highlight-photos"><img src="/2.jpeg" alt="Decoração infantil em azul e branco"/><img src="/5.jpeg" alt="Decoração de aniversário em azul e dourado"/></div></div></section>
    <section className="availability"><div className="container availability-inner"><div><p className="eyebrow">datas especiais pedem antecedência</p><h2>Vai comemorar <em>em breve?</em></h2><p>Escolha a data e consulte a disponibilidade para retirada dos itens.</p></div><div className="availability-action"><label htmlFor="availability-date">Data da festa</label><div className="availability-controls"><input ref={availabilityInput} id="availability-date" type="date" value={availabilityDate} onChange={(e) => setAvailabilityDate(e.target.value)}/><button className="button button-dark" onClick={checkAvailability}>{dateLabel ? `Consultar ${dateLabel} no WhatsApp` : "Escolha uma data"} <CalendarDays size={18}/></button></div><small>{dateLabel ? `Vamos perguntar sobre ${dateLabel} no WhatsApp.` : "Selecione o dia para criar sua mensagem automaticamente."}</small></div></div></section>
    <section className="section location"><div className="container location-grid"><div><p className="eyebrow">onde estamos</p><h2>Retire seus itens <em>em Osasco.</em></h2><p className="section-lead">A retirada e a devolução dos itens são feitas por quem contrata o serviço. Combine os horários conosco pelo WhatsApp.</p><div className="location-detail"><MapPin size={19}/><div><strong>{business.address}</strong><span>Ponto de retirada e devolução</span></div></div><div className="location-detail"><Clock3 size={19}/><div><strong>{business.hours}</strong><span>Horários de retirada e devolução a combinar</span></div></div><a className="button button-outline" href={`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(business.address)}`} target="_blank" rel="noreferrer">Ver endereço no mapa <ArrowRight size={17}/></a></div><div className="map-card"><iframe title="Mapa interativo do ponto de retirada da Festa na Mesa em Osasco" src={`https://maps.google.com/maps?q=${encodeURIComponent(business.address)}&z=16&output=embed`} loading="lazy" referrerPolicy="no-referrer-when-downgrade" allowFullScreen/><div className="map-card-footer"><span><MapPin size={18}/> Jardim Conceição · Osasco</span><a href={`https://www.google.com/maps/dir/?api=1&destination=${encodeURIComponent(business.address)}`} target="_blank" rel="noreferrer">Traçar rota <ArrowRight size={15}/></a></div></div></div></section>
    <section className="section faq" id="faq"><div className="container faq-grid"><div><p className="eyebrow">perguntas frequentes</p><h2>O que você quer <em>saber?</em></h2><p className="section-lead">Se a sua dúvida não aparecer aqui, é só mandar uma mensagem. A gente conversa.</p><button className="text-link" onClick={() => whatsapp("Olá! Tenho uma dúvida sobre a decoração.")}>Falar com a gente <ArrowRight size={16}/></button></div><div className="faq-list">{faqs.map(([question, answer], i) => <div className={`faq-item ${openFaq === i ? "open" : ""}`} key={question}><button onClick={() => setOpenFaq(openFaq === i ? -1 : i)} aria-expanded={openFaq === i}><span>{question}</span><ChevronDown size={19}/></button>{openFaq === i && <p>{answer}</p>}</div>)}</div></div></section>
    <section className="section instagram"><div className="container"><div className="section-heading"><div><p className="eyebrow"><Camera size={15}/> @festanamesa</p><h2>Acompanhe nossas <em>festas</em></h2></div><a className="text-link" href="https://instagram.com/festanamesa" target="_blank" rel="noreferrer">Ver Instagram <ArrowRight size={16}/></a></div><div className="insta-grid">{gallery.slice(0, 4).map((item) => <a href="https://instagram.com/festanamesa" target="_blank" rel="noreferrer" key={item.title}><img src={item.image} alt={item.title}/><span><Camera size={18}/></span></a>)}</div></div></section>
    <section className="final-cta"><div className="container final-inner"><div className="final-deco deco-a">✦</div><div className="final-deco deco-b">✧</div><p className="eyebrow">vamos celebrar</p><h2>Sua próxima comemoração<br/>pode <em>começar aqui.</em></h2><p>Conte o tema, a data e sua ideia.<br/>Você escolhe os itens e retira em Osasco.</p><button className="button button-light" onClick={() => whatsapp("Olá! Vim pelo site e gostaria de falar sobre a decoração da minha festa.")}>Falar no WhatsApp <MessageCircle size={18}/></button></div></section>
    <footer className="footer"><div className="container footer-grid"><div><Logo/><p className="footer-copy">Itens de decoração para festas cheias de carinho. Retirada e devolução em Osasco por conta de quem contrata.</p></div><div><h4>navegue</h4><a href="#sobre">Sobre a Festa na Mesa</a><a href="#decoracoes">Decorações</a><a href="#pacotes">Pacotes</a><a href="#faq">Dúvidas</a></div><div><h4>fale com a gente</h4><a href={`https://wa.me/${business.phone}`}>WhatsApp</a><a href="https://instagram.com/festanamesa" target="_blank" rel="noreferrer">Instagram</a><span>{business.address}</span><span>{business.hours}</span></div></div><div className="container footer-bottom"><span>© 2026 Festa na Mesa. Todos os direitos reservados.</span><span>Feito para celebrar.</span></div></footer>
    <button className="whatsapp-float" onClick={() => whatsapp("Olá! Vim pelo site e gostaria de fazer um orçamento.")} aria-label="Falar pelo WhatsApp"><MessageCircle size={26}/><span>fale com a gente</span></button>
    {selectedImage && <div className="lightbox" role="dialog" aria-modal="true" aria-label="Imagem ampliada" onClick={() => setSelectedImage(null)}><button className="lightbox-close" onClick={() => setSelectedImage(null)} aria-label="Fechar"><X size={22}/></button><img src={selectedImage.image} alt={selectedImage.title} onClick={(e) => e.stopPropagation()}/><div className="lightbox-caption"><strong>{selectedImage.title}</strong><span>{selectedImage.meta}</span></div></div>}
  </main>;
}

function PackageCard({ title, subtitle, items, onClick, featured = false }: { title: string; subtitle: string; items: string[]; onClick: () => void; featured?: boolean }) { return <div className={`package-card ${featured ? "featured" : ""}`}>{featured && <span className="popular">mais escolhido</span>}<span className="package-kicker">pacote {featured ? "02" : title === "Essencial" ? "01" : "03"}</span><h3>{title}</h3><p>{subtitle}</p><div className="package-divider"/><ul>{items.map((item) => <li key={item}><Check size={15}/>{item}</li>)}</ul><button className={featured ? "button button-primary" : "button button-outline"} onClick={onClick}>{title === "Essencial" ? "Consultar valor" : title === "Encanto" ? "Quero esse pacote" : "Personalizar pacote"} <ArrowRight size={16}/></button></div>; }
function Testimonial({ name, theme, text }: { name: string; theme: string; text: string }) { return <article className="testimonial"><div className="testimonial-top"><span className="avatar">{name.charAt(0)}</span><div><strong>{name}</strong><small>{theme}</small></div><span className="stars">★★★★★</span></div><p>“{text}”</p></article>; }
