"use client";

import { useMemo, useState } from "react";
import { ArrowRight, Balloon, CakeSlice, CalendarDays, Camera, Check, ChevronDown, Clock3, Gift, Heart, MapPin, Menu, MessageCircle, MoveRight, Palette, Sparkles, Star, X, WandSparkles } from "lucide-react";

const business = { name: "Festa na Mesa", phone: "5511999999999", city: "São Paulo e região", hours: "Seg a sex, 9h às 18h" };
const gallery = [
  { title: "Safari delicado", meta: "Aniversário infantil · 2 anos", image: "https://static.wixstatic.com/media/7f1a05_d44a171d7e734194aa85a8867ab191d8~mv2.png/v1/fill/w_1200,h_900,al_c,q_90,enc_avif,quality_auto/7f1a05_d44a171d7e734194aa85a8867ab191d8~mv2.png" },
  { title: "Arco pastel", meta: "Festa em casa · 30 anos", image: "https://d259o9es2o749h.cloudfront.net/wp-content/uploads/2022/10/19081958/DSC_2559ex-683x1024.jpg" },
  { title: "Chá revelação", meta: "Comemoração íntima", image: "https://cdn.othoba.com/images/thumbs/0711934_table-skirt-for-birthday-party-wedding-cake-table-decoration-pack-of-1-pcs.webp" },
  { title: "Unicórnio", meta: "Aniversário infantil · 5 anos", image: "https://i.pinimg.com/736x/f7/91/dc/f791dcf3f00c279680a6532d20401245.jpg" },
  { title: "Celebração leve", meta: "Festa feminina · 25 anos", image: "https://buildingandinteriors.com/wp-content/uploads/2022/11/ubuy-tulle-table-skirts.jpg" },
  { title: "Arco colorido", meta: "Aniversário · 7 anos", image: "https://i5.walmartimages.com/asr/5d161982-e28e-44e1-b5c1-4b96b554c1fc.98c4c3fc9fa94759fe26b17cf60aeb89.jpeg?odnBg=FFFFFF&odnHeight=900&odnWidth=900" },
];
const faqs = [["O que está incluso na decoração?", "Cada proposta é montada de acordo com o tema e o espaço. Pode incluir painel, mesa, suportes, bandejas, balões e itens decorativos."], ["Vocês montam no local?", "Sim. A montagem pode ser combinada conforme a região e o pacote escolhido."], ["Posso escolher qualquer tema?", "Sim — você pode enviar uma referência, escolher cores ou partir de um tema completo."], ["Com quanto tempo preciso reservar?", "Recomendamos consultar com 20 a 30 dias de antecedência. Para datas concorridas, quanto antes melhor."], ["Vocês trabalham com personagens?", "Sim, usamos personagens e elementos decorativos conforme disponibilidade e proposta."], ["O bolo e os doces estão inclusos?", "Não por padrão, mas podemos indicar parceiros e criar uma composição que valorize a mesa."], ["Posso personalizar as cores?", "Pode. A paleta é uma das partes mais gostosas de criar junto com você."], ["Vocês atendem fora da região?", "Atendemos São Paulo e cidades próximas. Consulte a possibilidade e a taxa de deslocamento."], ["Como funciona o pagamento?", "A reserva é confirmada após a aprovação da proposta e sinal combinado pelo WhatsApp."], ["Qual espaço mínimo preciso ter?", "A maioria das composições cabe em uma parede de aproximadamente 2 metros de largura."]];

function whatsapp(message: string) { window.open(`https://wa.me/${business.phone}?text=${encodeURIComponent(message)}`, "_blank", "noopener,noreferrer"); }
function Logo() { return <a href="#inicio" className="logo" aria-label="Festa na Mesa, início"><span className="logo-mark"><Balloon size={20} strokeWidth={1.8}/></span><span><strong>Festa</strong> na Mesa<small>decoração com carinho</small></span></a>; }

export default function Home() {
  const [menuOpen, setMenuOpen] = useState(false), [selectedImage, setSelectedImage] = useState<typeof gallery[number] | null>(null), [openFaq, setOpenFaq] = useState(0), [beforeAfter, setBeforeAfter] = useState(52);
  const [form, setForm] = useState({ occasion: "Aniversário infantil", theme: "", date: "", size: "Ainda não sei", place: "Casa", location: "" });
  const formMessage = useMemo(() => `Olá! Gostaria de solicitar um orçamento para Festa na Mesa.\n\nOcasião: ${form.occasion}\nTema: ${form.theme || "Ainda vou escolher"}\nData: ${form.date || "Ainda não definida"}\nTamanho: ${form.size}\nLocal: ${form.place}\nCidade/Bairro: ${form.location || "Não informado"}\n\nVi o trabalho de vocês pelo site.`, [form]);
  const update = (key: keyof typeof form, value: string) => setForm((current) => ({ ...current, [key]: value }));
  return <main>
    <header className="site-header"><div className="container nav-wrap"><Logo/><nav className={menuOpen ? "nav-links is-open" : "nav-links"} aria-label="Navegação principal">{[["Como funciona", "#como-funciona"], ["Decorações", "#decoracoes"], ["Pacotes", "#pacotes"], ["Avaliações", "#avaliacoes"], ["FAQ", "#faq"]].map(([label, href]) => <a key={href} href={href} onClick={() => setMenuOpen(false)}>{label}</a>)}</nav><button className="nav-cta" onClick={() => whatsapp("Olá! Vim pelo site e gostaria de fazer um orçamento.")}>Pedir orçamento <ArrowRight size={16}/></button><button className="menu-button" aria-label="Abrir menu" onClick={() => setMenuOpen(!menuOpen)}>{menuOpen ? <X/> : <Menu/>}</button></div></header>
    <section className="hero" id="inicio"><div className="container hero-grid"><div className="hero-copy"><p className="eyebrow"><span className="eyebrow-line"/> decoração que acolhe</p><h1>Sua festa linda,<br/><em>prática</em> e do seu jeito.</h1><p className="hero-lead">Decorações completas e personalizadas para transformar pequenos espaços em momentos inesquecíveis.</p><div className="hero-actions"><button className="button button-primary" onClick={() => whatsapp("Olá! Vim pelo site e gostaria de fazer um orçamento.")}>Quero meu orçamento <ArrowRight size={18}/></button><a className="button button-ghost" href="#decoracoes">Ver decorações <MoveRight size={18}/></a></div><div className="trust-row"><div><strong>+120</strong><span>festas montadas</span></div><div><strong>4.9<span>★</span></strong><span>avaliação média</span></div><div><strong>100%</strong><span>feito com carinho</span></div></div></div><div className="hero-visual"><div className="hero-image"><img src={gallery[0].image} alt="Mesa de festa decorada com balões e doces"/><div className="floating-note"><Sparkles size={15}/><span>cada detalhe<br/><b>pensado para você</b></span></div></div><div className="hero-orb orb-one"/><div className="hero-orb orb-two"/><span className="hero-stamp">feito<br/><b>à mão</b></span></div></div></section>
    <section className="proof-strip"><div className="container proof-items"><span><Palette size={18}/> montagem personalizada</span><span><WandSparkles size={18}/> temas variados</span><span><MessageCircle size={18}/> atendimento próximo</span><span><CakeSlice size={18}/> ideal para festas em casa</span></div></section>
    <section className="section about" id="sobre"><div className="container about-grid"><div><p className="eyebrow">o encanto está nos detalhes</p><h2>Uma festa bonita<br/><em>sem complicação.</em></h2><p className="section-lead">A Festa na Mesa é uma forma prática de ter uma decoração bonita e completa sem precisar montar uma grande estrutura de festa.</p><p className="section-lead">Preparamos uma composição pronta com painel, balões, bandejas, suportes e itens decorativos de acordo com o tema escolhido.</p><a className="text-link" href="#como-funciona">Entenda como funciona <ArrowRight size={16}/></a></div><div className="step-cards"><div className="step-card"><span>01</span><div><h3>Você escolhe o tema</h3><p>Conte o tema, as cores ou a ideia que você imaginou.</p></div></div><div className="step-card"><span>02</span><div><h3>Nós preparamos tudo</h3><p>Criamos uma composição harmoniosa e personalizada.</p></div></div><div className="step-card"><span>03</span><div><h3>Sua festa fica pronta</h3><p>Um cantinho especial para celebrar e fotografar.</p></div></div></div></div></section>
    <section className="section gallery-section" id="decoracoes"><div className="container"><div className="section-heading"><div><p className="eyebrow">portfólio</p><h2>Momentos que já <em>decoramos</em></h2></div><p>Inspirações reais para você encontrar o clima da sua próxima comemoração.</p></div><div className="gallery-grid">{gallery.map((item, index) => <button className={`gallery-item gallery-${index + 1}`} key={item.title} onClick={() => setSelectedImage(item)}><img src={item.image} alt={`${item.title}, ${item.meta}`}/><span className="gallery-caption"><strong>{item.title}</strong><small>{item.meta}</small></span><span className="gallery-plus">+</span></button>)}</div><div className="center-action"><button className="button button-outline" onClick={() => whatsapp("Olá! Gostei de uma decoração do site e gostaria de algo parecido.")}>Quero uma decoração assim <ArrowRight size={17}/></button></div></div></section>
    <section className="section benefits"><div className="container"><div className="section-heading centered"><div><p className="eyebrow">por que a gente</p><h2>Seu momento merece <em>cuidado</em></h2></div></div><div className="benefit-grid">{[[Heart, "Decoração personalizada", "Do tema às cores, tudo conversa com a sua ideia."], [Clock3, "Montagem prática", "Você aproveita a festa enquanto a gente cuida do cenário."], [Gift, "Opções para cada orçamento", "Uma proposta bonita que respeita o tamanho do seu momento."], [Star, "Composição fotogênica", "Detalhes pensados para render memórias — e fotos lindas."], [MapPin, "Atendimento próximo", "A gente responde, orienta e acompanha de verdade."], [Balloon, "Temas variados", "Do clássico ao criativo, sempre com leveza e bom gosto."]].map(([Icon, title, desc]) => <div className="benefit-card" key={title as string}><span className="icon-bubble"><Icon size={21}/></span><h3>{title as string}</h3><p>{desc as string}</p></div>)}</div></div></section>
    <section className="section packages" id="pacotes"><div className="container"><div className="section-heading"><div><p className="eyebrow">escolha seu jeito</p><h2>Pacotes para celebrar <em>sem estresse</em></h2></div><p>Comece com uma base ou conte sua ideia. A gente monta a melhor proposta.</p></div><div className="package-grid"><PackageCard title="Essencial" subtitle="Para comemorações simples" items={["painel", "mesa principal", "suportes", "itens decorativos", "composição temática"]} onClick={() => whatsapp("Olá! Gostaria de consultar o valor do Pacote Essencial.")}/><PackageCard featured title="Encanto" subtitle="O favorito para uma festa completa" items={["painel personalizado", "arco de balões", "mesa principal", "bandejas e arranjos", "personagens decorativos"]} onClick={() => whatsapp("Olá! Gostaria de saber mais sobre o Pacote Encanto.")}/><PackageCard title="Personalizado" subtitle="Para uma ideia só sua" items={["proposta sob medida", "espaço e tema", "quantidade de itens", "orçamento alinhado", "acompanhamento próximo"]} onClick={() => whatsapp("Olá! Quero montar um orçamento personalizado para a minha festa.")}/></div></div></section>
    <section className="section quote-section" id="orcamento"><div className="container quote-grid"><div className="quote-intro"><p className="eyebrow">vamos criar juntos</p><h2>Conte a ideia.<br/><em>A gente cuida do resto.</em></h2><p>Preencha rapidinho e receba uma conversa personalizada pelo WhatsApp. Sem compromisso.</p><div className="quote-note"><Check size={18}/> resposta rápida</div><div className="quote-note"><Check size={18}/> proposta de acordo com seu momento</div><div className="quote-note"><Check size={18}/> atendimento humano</div></div><div className="quote-card"><div className="form-progress"><span>01</span><div><b>Seu orçamento começa aqui</b><small>Leva menos de 1 minuto</small></div><Sparkles size={18}/></div><div className="form-grid"><label>Qual é a ocasião?<select value={form.occasion} onChange={(e) => update("occasion", e.target.value)}>{["Aniversário infantil", "Aniversário adulto", "Chá revelação", "Chá de bebê", "Mesversário", "Outra ocasião"].map((x) => <option key={x}>{x}</option>)}</select></label><label>Qual tema você deseja?<input placeholder="Ex.: Safari, azul e dourado" value={form.theme} onChange={(e) => update("theme", e.target.value)}/></label><label>Quando será a festa?<input type="date" value={form.date} onChange={(e) => update("date", e.target.value)}/></label><label>Qual tamanho da decoração?<select value={form.size} onChange={(e) => update("size", e.target.value)}>{["Pequena", "Média", "Completa", "Ainda não sei"].map((x) => <option key={x}>{x}</option>)}</select></label><label>Onde será realizada?<select value={form.place} onChange={(e) => update("place", e.target.value)}>{["Casa", "Salão", "Condomínio", "Outro"].map((x) => <option key={x}>{x}</option>)}</select></label><label>Cidade / bairro<input placeholder="Ex.: Moema, São Paulo" value={form.location} onChange={(e) => update("location", e.target.value)}/></label></div><button className="button button-primary form-submit" onClick={() => whatsapp(formMessage)}>Solicitar orçamento pelo WhatsApp <MessageCircle size={18}/></button><p className="form-footnote">Você será direcionado para uma conversa no WhatsApp.</p></div></div></section>
    <section className="section how" id="como-funciona"><div className="container"><div className="section-heading centered"><div><p className="eyebrow">é simples assim</p><h2>Do primeiro oi ao <em>parabéns</em></h2></div></div><div className="timeline">{[[MessageCircle, "Você chama no WhatsApp"], [Heart, "Conta sua ideia"], [Palette, "Escolhe tema e pacote"], [CalendarDays, "Confirmamos a data"], [WandSparkles, "Preparamos tudo"], [CakeSlice, "Sua festa fica pronta"]].map(([Icon, text], i) => <div className="timeline-item" key={text as string}><span className="timeline-number">{String(i + 1).padStart(2, "0")}</span><span className="timeline-icon"><Icon size={20}/></span><strong>{text as string}</strong></div>)}</div></div></section>
    <section className="section testimonials" id="avaliacoes"><div className="container"><div className="section-heading"><div><p className="eyebrow">de quem viveu</p><h2>Quem comemora com a gente <em>recomenda</em></h2></div><div className="rating"><span>★★★★★</span><b>4.9/5</b><small>avaliação média</small></div></div><div className="testimonial-grid"><Testimonial name="Mariana S." theme="Safari · 2 anos" text="A mesa ficou ainda mais linda do que eu imaginava. Tudo delicado, organizado e com muito capricho."/><Testimonial name="Camila R." theme="Chá revelação" text="O atendimento foi muito próximo desde o primeiro contato. Resolveram tudo e o resultado rendeu fotos maravilhosas."/><Testimonial name="Renata L." theme="Aniversário adulto" text="Consegui uma decoração elegante para a sala de casa. Prático, bonito e do jeitinho que eu queria."/></div></div></section>
    <section className="section before-after"><div className="container before-grid"><div className="compare-copy"><p className="eyebrow">olha a transformação</p><h2>Um cantinho simples pode virar o <em>destaque da festa.</em></h2><p>Uma composição bem pensada muda o clima do espaço — sem precisar de uma grande estrutura.</p><button className="text-link" onClick={() => whatsapp("Olá! Gostaria de transformar um cantinho da minha casa para uma festa.")}>Quero transformar meu espaço <ArrowRight size={16}/></button></div><div className="compare" aria-label="Comparação antes e depois"><img src={gallery[4].image} alt="Espaço de festa decorado"/><div className="compare-before" style={{ width: `${beforeAfter}%` }}><img src={gallery[4].image} alt="" style={{ filter: "grayscale(1) brightness(1.25) saturate(.2)" }}/></div><span className="compare-label before-label">antes</span><span className="compare-label after-label">depois</span><input type="range" min="15" max="85" value={beforeAfter} onChange={(e) => setBeforeAfter(Number(e.target.value))} aria-label="Mover comparação antes e depois"/><span className="compare-handle" style={{ left: `${beforeAfter}%` }}><MoveRight size={16}/></span></div></div></section>
    <section className="availability"><div className="container availability-inner"><div><p className="eyebrow">datas especiais pedem antecedência</p><h2>Vai comemorar <em>em breve?</em></h2><p>Algumas datas costumam ter maior procura. Consulte a disponibilidade para garantir seu tema.</p></div><button className="button button-dark" onClick={() => whatsapp("Olá! Gostaria de consultar disponibilidade para minha festa.")}>Consultar minha data <CalendarDays size={18}/></button></div></section>
    <section className="section location"><div className="container location-grid"><div><p className="eyebrow">onde estamos</p><h2>Atendemos sua festa <em>de perto.</em></h2><p className="section-lead">São Paulo e cidades próximas, com possibilidade de taxa de deslocamento. Consulte sua região pelo WhatsApp.</p><div className="location-detail"><MapPin size={19}/><div><strong>São Paulo e região</strong><span>Consulte bairros e cidades próximas</span></div></div><div className="location-detail"><Clock3 size={19}/><div><strong>{business.hours}</strong><span>Respondemos o mais rápido possível</span></div></div><button className="button button-outline" onClick={() => whatsapp("Olá! Gostaria de consultar se vocês atendem minha região.")}>Consultar minha região <ArrowRight size={17}/></button></div><div className="map-placeholder"><div className="map-pulse"><MapPin size={23}/></div><span>São Paulo<br/><small>e região</small></span><div className="map-road road-a"/><div className="map-road road-b"/><div className="map-road road-c"/></div></div></section>
    <section className="section faq" id="faq"><div className="container faq-grid"><div><p className="eyebrow">perguntas frequentes</p><h2>O que você quer <em>saber?</em></h2><p className="section-lead">Se a sua dúvida não aparecer aqui, é só mandar uma mensagem. A gente conversa.</p><button className="text-link" onClick={() => whatsapp("Olá! Tenho uma dúvida sobre a decoração.")}>Falar com a gente <ArrowRight size={16}/></button></div><div className="faq-list">{faqs.map(([question, answer], i) => <div className={`faq-item ${openFaq === i ? "open" : ""}`} key={question}><button onClick={() => setOpenFaq(openFaq === i ? -1 : i)} aria-expanded={openFaq === i}><span>{question}</span><ChevronDown size={19}/></button>{openFaq === i && <p>{answer}</p>}</div>)}</div></div></section>
    <section className="section instagram"><div className="container"><div className="section-heading"><div><p className="eyebrow"><Camera size={15}/> @festanamesa</p><h2>Acompanhe nossas <em>festas</em></h2></div><a className="text-link" href="https://instagram.com" target="_blank" rel="noreferrer">Ver Instagram <ArrowRight size={16}/></a></div><div className="insta-grid">{gallery.slice(0, 4).map((item) => <a href="https://instagram.com" target="_blank" rel="noreferrer" key={item.title}><img src={item.image} alt={item.title}/><span><Camera size={18}/></span></a>)}</div></div></section>
    <section className="final-cta"><div className="container final-inner"><div className="final-deco deco-a">✦</div><div className="final-deco deco-b">✧</div><p className="eyebrow">vamos celebrar</p><h2>Sua próxima comemoração<br/>pode <em>começar aqui.</em></h2><p>Conte o tema, a data e sua ideia.<br/>Nós cuidamos da decoração.</p><button className="button button-light" onClick={() => whatsapp("Olá! Vim pelo site e gostaria de falar sobre a decoração da minha festa.")}>Falar no WhatsApp <MessageCircle size={18}/></button></div></section>
    <footer className="footer"><div className="container footer-grid"><div><Logo/><p className="footer-copy">Decorações compactas e cheias de carinho para os momentos que merecem ser lembrados.</p></div><div><h4>navegue</h4><a href="#sobre">Sobre a Festa na Mesa</a><a href="#decoracoes">Decorações</a><a href="#pacotes">Pacotes</a><a href="#faq">Dúvidas</a></div><div><h4>fale com a gente</h4><a href={`https://wa.me/${business.phone}`}>WhatsApp</a><a href="https://instagram.com" target="_blank" rel="noreferrer">Instagram</a><span>{business.city}</span><span>{business.hours}</span></div></div><div className="container footer-bottom"><span>© 2026 Festa na Mesa. Todos os direitos reservados.</span><span>Feito para celebrar.</span></div></footer>
    <button className="whatsapp-float" onClick={() => whatsapp("Olá! Vim pelo site e gostaria de fazer um orçamento.")} aria-label="Falar pelo WhatsApp"><MessageCircle size={26}/><span>fale com a gente</span></button>
    {selectedImage && <div className="lightbox" role="dialog" aria-modal="true" aria-label="Imagem ampliada" onClick={() => setSelectedImage(null)}><button className="lightbox-close" onClick={() => setSelectedImage(null)} aria-label="Fechar"><X size={22}/></button><img src={selectedImage.image} alt={selectedImage.title} onClick={(e) => e.stopPropagation()}/><div className="lightbox-caption"><strong>{selectedImage.title}</strong><span>{selectedImage.meta}</span></div></div>}
  </main>;
}

function PackageCard({ title, subtitle, items, onClick, featured = false }: { title: string; subtitle: string; items: string[]; onClick: () => void; featured?: boolean }) { return <div className={`package-card ${featured ? "featured" : ""}`}>{featured && <span className="popular">mais escolhido</span>}<span className="package-kicker">pacote {featured ? "02" : title === "Essencial" ? "01" : "03"}</span><h3>{title}</h3><p>{subtitle}</p><div className="package-divider"/><ul>{items.map((item) => <li key={item}><Check size={15}/>{item}</li>)}</ul><button className={featured ? "button button-primary" : "button button-outline"} onClick={onClick}>{title === "Essencial" ? "Consultar valor" : title === "Encanto" ? "Quero esse pacote" : "Montar meu orçamento"} <ArrowRight size={16}/></button></div>; }
function Testimonial({ name, theme, text }: { name: string; theme: string; text: string }) { return <article className="testimonial"><div className="testimonial-top"><span className="avatar">{name.charAt(0)}</span><div><strong>{name}</strong><small>{theme}</small></div><span className="stars">★★★★★</span></div><p>“{text}”</p></article>; }
